Add CI-Connect CLI
keptn-sandbox/keptn-git-toolbox pull request #1
Opened 2021-08-31 12:10 UTC by thschue

2021-09-01 11:56 UTC, eugenbelsky approved these changes

2021-09-06 08:11 UTC, didiladi commented on .github/workflows/build.yaml
> +        component: [ "ci-connect-cli" ]
Using a matrix with only one component is an overkill.

2021-09-06 08:11 UTC, didiladi commented on .github/workflows/build.yaml
> +      - name: Run Trivy vulnerability scanner
:rocket:

2021-09-06 08:11 UTC, didiladi commented on ci-connect-cli/README.md
> +export GIT_REPO="https://github.com/<repo>"
This can also be a git repo not necessarily hosted by GitHub.

2021-09-06 08:11 UTC, didiladi commented on ci-connect-cli/cmd/fileutils.go
> +/* MIT License
This comment should be at the top of the file.

2021-09-06 08:11 UTC, didiladi commented on ci-connect-cli/cmd/gitutils.go
> +package cmd
The apache file header is missing from all the shource files.

2021-09-06 08:11 UTC, didiladi commented on ci-connect-cli/cmd/version.go
> +const version = "0.0.7"
Might make sense to increate the version to `0.1` or even `1.0.0`.

2021-09-06 08:11 UTC, didiladi commented on ci-connect-cli/go.mod
> +	github.com/go-git/go-git/v5 v5.4.2
Without the patch of @yeahservice (`github.com/yeahservice/go-git/v5 v5.4.2-aws-patch`), using an AWS code commit repository for the keptn git repo will not be possible.

2021-09-06 08:11 UTC, didiladi commented on ci-connect-cli/main.go
> +Copyright © 2021 NAME HERE <EMAIL ADDRESS>
`2021 NAME HERE <EMAIL ADDRESS>`

2021-09-06 08:14 UTC, yeahservice requested changes

2021-09-06 08:14 UTC, yeahservice commented on ci-connect-cli/README.md
> +Example configurations for testing can be found in the `.keptn` and `helm` directories
Can remove this line since there are no configuration examples

2021-09-06 08:28 UTC, yeahservice requested changes

2021-09-06 08:28 UTC, yeahservice commented on ci-connect-cli/helm/test-service/values.yaml
> +test
Can remove this file without the other testing files of `.keptn` it does nothing

2021-09-09 11:22 UTC, merged