Add operator
keptn-sandbox/keptn-git-toolbox pull request #3
Opened 2021-09-01 05:21 UTC by thschue

2021-09-01 11:55 UTC, eugenbelsky approved these changes

2021-09-01 11:56 UTC, eugenbelsky approved these changes

2021-09-06 08:23 UTC, yeahservice requested changes

2021-09-06 08:23 UTC, yeahservice commented on .github/workflows/build.yaml
> +        component: [ "ci-connect-cli", "promotion-service", "git-operator" ]
This workflow apparently builds all components already, I guess the workflows from other the other PRs can be dropped.

2021-09-06 12:47 UTC, didiladi commented on git-operator/chart/Chart.yaml
> +version: 0.1.0
Should we align the versions of connect-cli, operator, and promotion-service?

2021-09-06 12:47 UTC, didiladi commented on git-operator/chart/values.yaml
> +apiUrl: "http://api-gateway-nginx/api"
`api-gateway`?

2021-09-06 12:47 UTC, yeahservice requested changes

2021-09-06 12:47 UTC, yeahservice commented on git-operator/README.md
> +**A Helm Chart will be created soon**
Helm chart already exists now, a short documentation on how to use it would be awesome

2021-09-06 12:47 UTC, yeahservice commented on git-operator/README.md
> +* Currently Services are created regardless if they exist or not, this leads to many "create" events shown in the
This we resolved already at some point in the past

2021-09-06 12:47 UTC, yeahservice commented on git-operator/chart/README.md
> +| `helmservice.image.repository` | Container image name | `"docker.io/keptn/keptn-gitops-operator"` |
For the keptn-sandbox repository the following should be the correct docker organization

```suggestion
| `helmservice.image.repository` | Container image name | `"docker.io/keptnsandbox/keptn-gitops-operator"` |
```

2021-09-06 12:57 UTC, didiladi requested changes

2021-09-06 12:57 UTC, didiladi commented on .github/workflows/build.yaml
> +    steps:
Please execute the unit tests of all 3 components within the workflow.

2021-09-09 11:21 UTC, merged